import "./globals.css";
import "@/lib/fontawesome";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Ro.Manic | Маникюр твоей мечты",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className='antialiased'>
        <Header />
        <div className="flex flex-row justify-center mt-25">
          <main className="container min-h-screen">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
