services:
  backend:
    build: ./backend
    container_name: courses_backend
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /usr/local/bundle
    environment:
      - DATABASE_URL=postgres://backend_user:password@db:5432/myapp_development
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: courses_frontend
    command: sleep infinity
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - API_URL=http://localhost:3000
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000

  db:
    image: postgres:16
    container_name: courses_db
    restart: always
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"