services:
  backend:
    build: ./backend
    container_name: courses_backend
    # command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://backend_user:password@db:5432/myapp_development
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: courses_frontend
    # command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://localhost:3000

  db:
    image: postgres:16
    container_name: courses_db
    restart: always
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"